version: '3.7'

services:
  kurento-monitoring-server:
    image: kurento-monitoring
    build:
      context: .
    container_name: kurento-monitoring-server
    ports:
      - "3333:3333"
    command: ["npm", "start"]